#!/bin/sh

# getSRA version
VERSION="0.6"

# default arguments
OUTDIR="./"
NTHREADS=`grep -c ^processor /proc/cpuinfo`

# functions for version and help
print_version(){
  echo "getSRA version $VERSION"
}

print_help(){
  cat <<EOS
Usage:
getSRA -t <number of threads> -s <sra id> -n <sample name>

getSRA option:
-t|--threads         number of threads [default: number of cores on your systerm]
-s|--sra-id          SRA id
-a|--accession-list  Accession list
-o|--outdir          output directory [default: cwd]
-n|--name            sample name
-k|--keep            keep sra file

Extra arguments will be passed through

Other:
-v|--version         show version info
-h|--help            program usage
EOS
}

# parse arguments
while [[ $# -gt 0 ]]; do
  key=${1}
  case ${key} in
    -v|--version)
      print_version
      exit 0
      ;;
    -h|--help)
      print_help
      exit 0
      ;;
    -t|--threads)
      NTHREADS=${2}
      shift
      ;;
    -s|--sra-id)
      SRAID=${2}
      shift
      ;;
    -o|--outdir)
      OUTDIR="${2}"
      shift
      ;;
    -a|--accession-list)
      ACCESSION=${2}
      shift
      ;;
    -n|--name)
      NAME=${2}
      shift
      ;;
    -k|--keep)
      KEEP="${OPTIONS} ${1}"
      shift
      ;;
    -Z|--stdout)
      STDOUT="true"
      ;;
    -*|--*)
      OPTIONS="${OPTIONS} ${1}"
      # OPTIONS="${OPTIONS} ${1} ${2}"
      ;;
    *sra)
      INPUT_FILES="${INPUT_FILES} ${1}"
      ;;
    *)
      OPTIONS="${OPTIONS} ${1}"
  esac
  shift
done

if [[ ${OUTDIR} == */ ]]; then
  OUTDIR="${OUTDIR%*/}"
else
  :
fi

mkdir -p ${OUTDIR}/tmp

if [[ "${SRAID}" ]]; then
  prefetch --output-directory ${OUTDIR}/tmp ${SRAID};
  INPUT_FILES=${OUTDIR}/tmp/*.sra
elif [[ "${ACCESSION}" ]]; then
  prefetch --output-directory ${OUTDIR}/tmp --option-file ${ACCESSION};
elif [[ "${INPUT_FILES}" ]]; then
  :
else
  echo "ERROR: No SRA ID."
  exit 1
fi

third2second(){
  local sra_id=${1}
  cat ${OUTDIR}/tmp/${sra_id}_3.fastq | sed -e 's/reverse\/3/reverse\/2/g' > ${OUTDIR}/tmp/${sra_id}_2.fastq
  rm ${OUTDIR}/tmp/${sra_id}_3.fastq
}

compress(){
  local sra_id=${1}
  local idx=${2}
  if [ -f ${OUTDIR}/tmp/${sra_id}_3.fastq ]; then third_file=${OUTDIR}/tmp/${sra_id}_3.fastq; fi
  if [[ "${NAME}" ]]; then
    if [[ "${third_file}" ]]; then third2second ${sra_id}; fi
    pigz -p ${NTHREADS} -c ${OUTDIR}/tmp/${sra_id}_1.fastq > ${OUTDIR}/tmp/${NAME}-${idx}_1.fastq.gz; rm ${OUTDIR}/tmp/${sra_id}_1.fastq;
    pigz -p ${NTHREADS} -c ${OUTDIR}/tmp/${sra_id}_2.fastq > ${OUTDIR}/tmp/${NAME}-${idx}_2.fastq.gz; rm ${OUTDIR}/tmp/${sra_id}_2.fastq;
  else
    if [[ "${third_file}" ]]; then third2second ${sra_id}; fi
    for fastq in ${OUTDIR}/tmp/*.fastq; do pigz -p ${NTHREADS} ${fastq}; done
  fi
}

fastq_dump_sra(){
  idx=1
  for file in ${INPUT_FILES}; do
    local sra_id=$(basename ${file} .sra)
    pfastq-dump -t ${NTHREADS} -O ${OUTDIR}/tmp --split-files --skip-technical --defline-qual '+' --defline-seq '@$sn[_$rn]/$ri' ${file}
    compress ${sra_id} ${idx}
    let idx++
  done
}

fastq_dump_accession(){
  idx=1
  cat ${ACCESSION} | while read line || [ -n "${line}" ]; do
    local sra_id=${line}
    pfastq-dump -t ${NTHREADS} -O ${OUTDIR}/tmp --split-files --skip-technical --defline-qual '+' --defline-seq '@$sn[_$rn]/$ri' ${OUTDIR}/tmp/${sra_id}.sra
    compress ${sra_id} ${idx}
    let idx++
  done
}



# cd ${OUTDIR}/tmp
if [[ "${ACCESSION}" ]]; then
  fastq_dump_accession
else
  fastq_dump_sra
fi

mv -bv ${OUTDIR}/tmp/*.fastq.gz ${OUTDIR}

if [[ "${KEEP}" ]]; then
  mv -b ${OUTDIR}/tmp ${OUTDIR}/sra
else
  rm -r ${OUTDIR}/tmp
fi